<a href="https://colab.research.google.com/github/dhuy228/matipulate-matrix/blob/master/reverse-element-order.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="45px" src="https://colab.research.google.com/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>The equivalent of np.flip(data,(0,2)) using np.flipud and np.fliplr</h1>

Classic case when some packages need numpy  < 1.12.0, you would meet this Attribute Error

For more details: https://stackoverflow.com/questions/45706896/attributeerror-module-numpy-has-no-attribute-flip

This notebook shows a way to work around it using np.flipud() and np.fliplr()


In [0]:
import numpy as np

In [4]:
A = np.arange(8).reshape(2,2,2)
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [5]:
np.flip(A,(0,2))

array([[[5, 4],
        [7, 6]],

       [[1, 0],
        [3, 2]]])

In [17]:
np.flipud(A)[:,:,::-1,...]

array([[[5, 4],
        [7, 6]],

       [[1, 0],
        [3, 2]]])

Here this code shows that **np.flip(A,(0,2)) == np.flipud(A)[:,:,::-1,...]**

In [25]:
# Another example
B = np.arange(27).reshape(3,3,3)
B

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [26]:
np.flip(B,(0,2))

array([[[20, 19, 18],
        [23, 22, 21],
        [26, 25, 24]],

       [[11, 10,  9],
        [14, 13, 12],
        [17, 16, 15]],

       [[ 2,  1,  0],
        [ 5,  4,  3],
        [ 8,  7,  6]]])

In [27]:
np.flipud(B)[:,:,::-1,...]

array([[[20, 19, 18],
        [23, 22, 21],
        [26, 25, 24]],

       [[11, 10,  9],
        [14, 13, 12],
        [17, 16, 15]],

       [[ 2,  1,  0],
        [ 5,  4,  3],
        [ 8,  7,  6]]])

In [28]:
np.all(np.flip(B,(0,2)) == np.flipud(B)[:,:,::-1,...])

True

Example on non-square matrix

In [39]:
# Non-square matrix
C = np.arange(53477376).reshape(512,512,204)
np.all(np.flip(C,(0,2)) == np.flipud(C)[:,:,::-1,...])

True